DutchTreat/Controllers/AppController.cs
using DutchTreat.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using DutchTreat.Service;
using DutchTreat.Data.Entities;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using DutchTreat.Data;

namespace DutchTreat.Controllers
{
    public class AppController : Controller 
    {
        private readonly IMailService _mailservice;
        //private readonly DutchContext _context;
        private readonly IDutchRepository _repository;
        //public AppController(IMailService mailService, DutchContext context)
        //{
        //    this._mailservice = mailService;
        //    _context = context;
        //}
        public AppController(IMailService mailService, IDutchRepository repository)
        {
            this._mailservice = mailService;
            _repository = repository;
        }

        public IActionResult Index()
        {
            //throw new InvalidOperationException("Something bad");

            // ici c'est pour montrer que le chargement de Scope a fonctionné 
           // var result = _context.Products.ToList();

             return View();
        }
        [HttpGet("Contact")]
        public IActionResult Contact()
        {
          //throw new InvalidOperationException("Something bad");
            ViewBag.Title = "Contact Us";
            return View();
        }
        [HttpPost("Contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if(ModelState.IsValid)
            {
                // Send a email
                _mailservice.SendMessage("nbvoice@gmail.com", model.Subject,model.Message);
                ViewBag.UserMessage = "Send email";
                ModelState.Clear();
            }
            else
            {
                //Error
            }           
            return View();
        }
        [HttpGet("About")]
        public IActionResult About()
        {
            ViewBag.Title = "About Us";
            return View();
        }
        public IActionResult Shop()
        {

            // Cette requete sera remplacé par le repository 
            //var result = _context.Products
            //    .OrderBy(p => p.Category)
            //    .Select(p => p)
            //    .ToList();

            //var result2 = from p in _context.Products
            //              orderby p.Category
            //              select p;

            var result = _repository.GetAllProducts();
           
            return View(result.ToList());
        }

    }
}

DutchTreat/Controllers/ProductsController.cs
using DutchTreat.Data;
using DutchTreat.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.Controllers
{
    [Route("api/[Controller]")]
    [ApiController]
    [Produces("application/json")]
    public class ProductsController : Controller
    {
        private readonly IDutchRepository _repository;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(IDutchRepository repository, ILogger<ProductsController> logger)
        {
            this._repository = repository;
            this._logger = logger;
        }

        //[HttpGet]
        //public JsonResult Get()
        //{
        //    try
        //    {
        //        return Json(_repository.GetAllProducts());
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.LogError("Faild to send data product");
        //        return Json("Bad Request");
        //    }
            
        //}
        [HttpGet]
        [ProducesResponseType(200)]
        [ProducesResponseType(400)]
        public IActionResult<IEnumerable<Product>> Get()
        {
            try
            {
                return Ok(_repository.GetAllProducts());
            }
            catch (Exception ex)
            {
                _logger.LogError($"Faild to send data product {ex}");
                return BadRequest("Bad Request");
            }

        }

    }
}

DutchTreat/Views/App/About.cshtml
<h2>About Us</h2>
<p>More to follow</p>

<div id="theForm">
    <form>
        <label>Your Name:</label>
        <br />
        <input />
        <br />
        <label>Email:</label>
        <br />
        <input type="email" />
        <br />
        <label>Subject:</label>
        <br />
        <input type="text" />
        <br />
        <label>Message:</label>
        <br />
        <textarea rows="4"></textarea>
        <br />
        <input type="submit" value="Send Message" />
    </form>
</div>

DutchTreat/Views/App/Contact.cshtml
@model ContactViewModel
<h2>@ViewBag.Title</h2>

<form method="post">
    <script src="~/jquery-validate/jquery.validate.min.js"></script>

    <div asp-validation-summary="ModelOnly"></div>

    <label asp-for="Name">Your Name:</label>
    <br />
    <
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <br />

    <label asp-for="Email">Email:</label>
    <br />
    <input type="email" asp-for="Email" />
    <span asp-validation-for="Email"></span>
    <br />
    <label asp-for="Subject">Subject:</label>
    <br />
    <input type="text" asp-for="Subject" />
    <span asp-validation-for="Subject"></span>
    <br />
    <label asp-for="Message">Message:</label>
    <br />
    <textarea rows="4" asp-for="Message"></textarea>
    <br />
    <input type="submit" value="Send Message" />
    <div>@ViewBag.UserMessage</div>
</form>

DutchTreat/Views/App/Shop.cshtml
@model IEnumerable<Product>
<h1>Shop</h1>

<p>@Model.Count()</p>

@foreach (var p in Model)
{
    <li>@p.Title</li>
}

DutchTreat/Views/App/index.cshtml
@{ ViewBag.Title = "Home Page"; }


<div class="product-info">
    <img src="~/img/VanGogh.jpg">
    <h3>Mug</h3>
    <ul class="product-props">
        <li>Price: $9.99</li>
        <li>Artist: Van Gogh</li>
        <li>Title: </li>
        <li>Description: Self-portrait</li>
    </ul>
    <button>Buy</button>
</div>

<div id="theForm">
    <form>
        <label>Your Name:</label>
        <br />
        <input />
        <br />
        <label>Email:</label>
        <br />
        <input type="email" />
        <br />
        <label>Subject:</label>
        <br />
        <input type="text" />
        <br />
        <label>Message:</label>
        <br />
        <textarea rows="4"></textarea>
        <br />
        <input type="submit" value="Send Message" />
    </form>
</div>

DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat : @ViewBag.Title</title>
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <h2>@ViewBag.Title</h2>

    <header>
        <h1>Welcome to Dutch Treat</h1>
        <menu>
            <ul>
                <li><a asp-controller="APP" asp-action="Index">Home</a></li>
                <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                <li><a asp-controller="App" asp-action="About">About</a></li>
                
            </ul>
        </menu>
    </header>
    
    <section>
        <h2>@ViewBag.Title</h2>
       @RenderBody()
    </section>
    
    <footer>Copyright 2017 Dutch Treat 2017</footer>

    

</body>
</html>